language: node_js
node_js:
  - "6"
env:
  global:
    - BUILD_HOMEPAGE=https://github.jpl.nasa.gov/pages/CommonMappingClient/cmc-core/$TRAVIS_BRANCH
cache:
  directories:
    - node_modules
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - chmod a+x deploy.bash
script: 
  - npm run build
  - npm run test:cover
  - npm run deploy
# after_success:
  # Send coverage data to coveralls.
  # - npm run test:cover:travis
  # - chmod a+x deploy.sh
  # - ./deploy.sh
notifications:
  email: false
  slack: 
    rooms: 'jpl:aIhKT9PPFqBrGZxYBva6mEJx'
    on_pull_requests: false
    template:
      - "[%{branch}] build <%{build_url}|#%{build_number}> of (<%{compare_url}|%{commit}>) by %{author} %{result} in %{duration}"