language: node_js
node_js:
  - "6"
env:
  global:
    - BUILD_HOMEPAGE=https://github.jpl.nasa.gov/pages/$TRAVIS_REPO_SLUG/branches/$TRAVIS_BRANCH
cache:
  directories:
    - node_modules
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - chmod a+x scripts/deploy.bash
script: 
  - npm run build
  - npm run test:cover
  - npm run deploy
notifications:
  email: false
  slack: 
    rooms: 'jpl:aIhKT9PPFqBrGZxYBva6mEJx'
    on_pull_requests: false
    on_start: always
    template:
      - "%{repository} [%{branch}] \nBuild <%{build_url}|#%{build_number}> for commit (<%{compare_url}|%{commit}>) by %{author}\n %{result} in %{duration}\n Deployed to <https://github.jpl.nasa.gov/pages/%{repository_slug}/branches/%{branch}}|#github_pages>\n - %{commit_subject}"