language: node_js
node_js:
  - "6"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script: 
  - npm run build
  - npm run test
# after_success:
  # Send coverage data to coveralls.
  # - npm run test:cover:travis
  # - chmod a+x deploy.sh
  # - ./deploy.sh
notifications:
  email: false