language: node_js
node_js:
  - "6"
script: 
  - npm run build
  - npm run test
# after_success:
  # Send coverage data to coveralls.
  # - npm run test:cover:travis
  # - chmod a+x deploy.sh
  # - ./deploy.sh
notifications:
  email: false